### ISSUE TITLE
AttributeError: module 'ruamel.yaml' has no attribute 'CommentedMap'

### ISSUE THREAD

**Issue by sjanuth** [rauc-lab/being#18]
Can occur when reading parameter config values from a file.
Latest RUAMEL_YAML package (version 0.17.21) throws this error. Works fine with version 0.17.19
